name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # No external dependencies required for basic functionality

    - name: Test GUI availability
      run: |
        python -c "import tkinter; print('tkinter available')"
      # Skip GUI test on headless systems
      continue-on-error: true

    - name: Test imports
      run: |
        python -c "import sys; sys.path.append('src'); from integrators import ArticleIntegrator"

    - name: Run basic functionality test
      run: |
        python -c "
        import sys
        sys.path.append('src')
        from integrators.article_integrator import ArticleIntegrator
        integrator = ArticleIntegrator()
        print('Basic integrator creation successful')
        "

    - name: Test sync utility
      run: |
        python sync_site.py status || echo 'Sync utility test (expected to fail without content)'